name: Get Repositories
on:
  workflow_dispatch:

jobs:
 execute:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: script execute permission
      #run:  chmod +x tmcr.sh
      run:  chmod +x tmcr1.sh

    - name: Run Create Teams Script
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #run: bash tmcr.sh
      run: bash tmcr1.sh
